"""Generate crawlable, standalone promotional pages and shared place metadata."""
from pathlib import Path
import json,html,re
BASE='https://departurebayspeedway.scroggygames.com'
google_tag='<!-- Google tag (gtag.js) -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-HR9RQXCV2F"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n  gtag(\'config\', \'G-HR9RQXCV2F\');\n</script>'
place={'@type':'Place','@id':BASE+'/#departure-bay','name':'Departure Bay Road, Nanaimo','description':'The Nanaimo, British Columbia road and coastal neighbourhood depicted in Departure Bay Speedway.','address':{'@type':'PostalAddress','streetAddress':'Departure Bay Road','addressLocality':'Nanaimo','addressRegion':'BC','addressCountry':'CA'},'containedInPlace':{'@type':'City','name':'Nanaimo','sameAs':'https://www.nanaimo.ca/'}}
game={'@type':'VideoGame','@id':BASE+'/#game','name':'Departure Bay Speedway','url':BASE+'/','description':'A free browser dirtbike game inspired by Departure Bay Road in Nanaimo, from Country Club to the beach. Ride with up to seven named players and throw Nanaimo bars in a fictional local satire.','genre':['Racing','Arcade'],'gamePlatform':'Web browser','applicationCategory':'GameApplication','operatingSystem':'Any with a modern WebGL-capable browser','inLanguage':'en-CA','isAccessibleForFree':True,'playMode':'https://schema.org/MultiPlayer','numberOfPlayers':{'@type':'QuantitativeValue','minValue':1,'maxValue':7},'contentLocation':{'@id':BASE+'/#departure-bay'},'gameLocation':{'@id':BASE+'/#departure-bay'},'image':BASE+'/openingscreen.jpg','screenshot':[BASE+'/assets/promo/game-downhill.jpg',BASE+'/assets/promo/game-beach.jpg']}
arrow='<svg viewBox="0 0 30 20" aria-hidden="true"><path d="M0 10h27M19 2l8 8-8 8"/></svg>'
cta='<a class="cta" href="/">Play the game '+arrow+'</a>'
links=[('nanaimo-dirtbike-game.html','The game'),('departure-bay-road.html','The route'),('loud-dirtbikes-nanaimo.html','Neighbourhood noise')]
def picture(name,caption,slant=False):return f'<figure class="picture {"slant" if slant else ""}"><img src="/assets/promo/{name}.jpg" alt="{html.escape(caption)}" width="1440" height="900" loading="lazy"><figcaption>{caption}</figcaption></figure>'
def faq(items):return '<section class="wrap faq"><h2>A few things, bud.</h2>'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</section>'
party='''<section class="party"><div class="party-inner"><div><h2>Bring six buddies.<br>Or six bad influences.</h2><p>Seven riders. Seven colours. Your name above your bike. See the other players tearing down the same road while you chase your own score. Full room? Rock, paper, scissors keeps your hands busy until your spot opens.</p><a class="text-link" href="/">Get your name on a bike →</a></div><div><div class="roster" aria-label="Seven player colours">'''+''.join(f'<span style="--c:{c};--r:{r}deg"></span>' for c,r in zip(['#f04452','#268aff','#32d583','#ffd23f','#bd75ff','#ff8a32','#f064c8'],[-9,5,-5,9,-7,3,8]))+'''</div><p>Same road. Separate scores. Plenty of local character.</p></div></div></section>'''
closing='<section class="closing"><h2>See you at the beach.</h2><p>Helmet on. Bars loaded. Give ’er.</p>'+cta+'</section>'
pages=[
{'file':links[0][0],'title':'Nanaimo Dirtbike Game | Departure Bay Speedway','desc':'Ride Departure Bay Road from Country Club to the beach. A free Nanaimo browser game with seven named riders, flying Nanaimo bars and local character.','heading':'Dirtbike.<br>Dirtbag.<br><em>Dessert delivery.</em>','lead':'You’re a dirt biking dirtbag, armed with Nanaimo bars and ready to party. Welcome to Departure Bay Speedway, bud.','hero':'downhill-hero','body':
'<section class="paper"><div class="wrap split"><div><h2>Your usual road.<br>A very unusual commute.</h2><p>That downhill run from Country Club to Departure Bay Beach? We made a whole dirtbike game out of it. The corners, the trees, the roadside characters. Then we added airborne custard.</p><p>A little look into life on Nanaimo’s Departure Bay Speedway—through the deeply questionable judgement of one fictional dirtbag.</p><a class="text-link" href="/departure-bay-road.html">Take a look down the road →</a></div>'+picture('game-downhill','Actual game capture — riding the Departure Bay Road simulation.',True)+'</div></section>'+
'<section class="wrap"><div class="section-intro"><h2>Holy crap, bud.<br>That’s our neighbourhood.</h2><p>Transit buses. Hillside homes. Deer with terrible timing. A road to the water that gets more familiar with every refinement.</p></div>'+picture('game-street','Actual game capture — the street, traffic and local scenery.')+'<p class="local-quote">“A frikkin’ Nanaimo bar! You terd!”</p><p>Wheelies, jumps, close calls and dessert-based bad decisions. Our cast has plenty to say about your driving. Mute is there when the household has heard quite enough, thanks.</p></section>'+party+
faq([('Is Departure Bay Speedway free?','Yep, bud. Play in your browser. No download or account required—enter a rider name and join.'),('Is this an exact road or driving simulator?','It is a stylised arcade game based on Departure Bay Road. We use street references and terrain data, but scenery and physics are adapted for play and are still being refined.'),('How do I ride?','Use W or the up arrow to accelerate, S to brake, A/D to steer, Space to jump and F to throw a Nanaimo bar. Touch controls appear on supported phones.'),('Can my friends see me?','Yes. Up to seven active riders share the room, with names and individual colours. Traffic, pedestrians and scoring run locally for each player.')])+closing},
{'file':links[1][0],'title':'Departure Bay Road Simulator | Country Club to the Beach','desc':'Explore the Nanaimo road behind Departure Bay Speedway. Country Club, familiar roadside scenery and the beach finish, with real in-game screenshots.','heading':'Country Club<br>to the beach.<br><em>Give ’er.</em>','lead':'A neat little Departure Bay Road simulator with a very Nanaimo sense of humour. You know the trip. This time, you’re bringing the bars.','hero':'beach-hero','body':
'<section class="paper"><div class="wrap split"><h2>The coast is calling.<br>Your brakes have concerns.</h2><div><p>The game follows a roughly 2.9-kilometre route from the Country Club area down toward Departure Bay Beach in Nanaimo, British Columbia. A familiar everyday road becomes a ridiculous little downhill adventure.</p><p>Real street references guide the layout. The hero, dialogue, chases and flying desserts belong firmly to the game.</p></div></div></section>'+
'<section class="wrap"><div class="section-intro"><h2>Know these corners?</h2><p>These are captures from the actual game. The illustrated hero scenes are campaign art.</p></div><article class="chapter"><span class="place">COUNTRY CLUB</span><div><h3>Start your nonsense.</h3><p>Enter your name, claim a colour and get settled on the bike. The route begins near Country Club, with the beach waiting downhill.</p></div>'+picture('game-downhill','In-game road on the downhill run.')+'</article><article class="chapter"><span class="place">DEPARTURE BAY ROAD</span><div><h3>Easy there, pal.</h3><p>Roadside shops, school-area scenery, retaining walls and forest edges give the ride its local flavour. Keep your eyes up. The deer did not read the itinerary.</p></div>'+picture('game-street','In-game roadside scenery and traffic.')+'</article><article class="chapter"><span class="place">THE BEACH</span><div><h3>Made it. Mostly.</h3><p>Finish by the water, check your score and have another go. The coast is lovely. Your imaginary insurance premium, less so.</p></div>'+picture('game-beach','In-game approach to the Departure Bay waterfront.')+'</article></section>'+party+faq([('Where is Departure Bay Road?','Departure Bay Road is in Nanaimo on Vancouver Island, British Columbia. The game depicts the run from the Country Club area toward Departure Bay Beach.'),('Does the artwork show the exact road?','The large hero illustrations are fictional campaign art. Images captioned as game captures show the current simulation. Neither is a navigation guide.'),('What makes it Nanaimo?','The setting, the hills, the coastal finish, the Nanaimo bars and a cast with plenty of “holy crap, bud” energy. The game is local satire, not a claim about particular residents.')])+closing},
{'file':links[2][0],'title':'Loud Dirtbikes in Nanaimo? A Quieter Kind of Road Rage','desc':'Loud dirtbikes in Nanaimo getting on your nerves? Find the City’s noise information, then take a fictional spin in Departure Bay Speedway—with a mute button.','heading':'Loud bikes?<br><em>We put ours<br>on mute.</em>','lead':'You wanted a quiet afternoon, pal. The neighbourhood soundtrack had other ideas. Here’s a little Departure Bay escape you can turn down.','hero':'downhill-hero','body':
'<section class="paper"><div class="wrap split"><div><h2>For the real noise,<br>start here, bud.</h2><p>If you came here asking how to deal with loud dirtbikes or motorcycle noise in Nanaimo, the City’s noise information is a useful place to start. It explains its complaint process and contact options.</p><div class="noise-note"><h3>Actual neighbourhood issue?</h3><p><a href="https://www.nanaimo.ca/public-safety/city-bylaws/bylaw-complaints/noise-bylaw">Read the City of Nanaimo’s noise information →</a></p><p>This page promotes a fictional browser game. We don’t take complaints or represent the City.</p></div></div><div><h2>For imaginary road rage,<br>we brought snacks.</h2><p>Departure Bay Speedway turns a familiar Nanaimo commute into an arcade romp. You’re the dirt biking dirtbag this time: white helmet, red bike, Nanaimo bars at the ready.</p><p>Keep the chaos on screen, dial down the sound and give the neighbours their afternoon back. Press M in the game to mute.</p><a class="text-link" href="/">Take the virtual ride →</a></div></div></section>'+
'<section class="wrap"><div class="section-intro"><h2>Love the neighbourhood.<br>Laugh at the nonsense.</h2><p>School traffic. A bus round the bend. That glorious glimpse of the bay. A wildly fictional day on a very familiar road.</p></div>'+picture('game-street','Actual game capture — a fictional ride through familiar Nanaimo scenery.')+'<p class="local-quote">All the “watch it, bud!”<br>With a volume control.</p><p>We’re poking fun at an over-the-top game character. The real people on Departure Bay Road are our audience, not our targets. Grab a buddy, pick a name and see who gets to the beach in better shape.</p></section>'+faq([('How can I deal with loud dirtbikes in Nanaimo?','For real-world noise concerns, start with the <a href="https://www.nanaimo.ca/public-safety/city-bylaws/bylaw-complaints/noise-bylaw">City of Nanaimo’s noise information and complaint options</a>. This game cannot receive or resolve complaints.'),('Can I play without the engine noise?','Yes. Press M to mute game audio. The waiting-room beat sound is optional and starts switched off.'),('Is this an official Nanaimo simulator?','No, bud. Departure Bay Speedway is an independent fictional arcade game inspired by the local road and neighbourhood.'),('Can I play with other Nanaimo residents?','The shared room supports seven active players. Each enters a display name and gets a different colour; extra players wait for a spot.')])+closing}
]
for p in pages:
 nav='<nav class="nav"><a class="brand" href="/nanaimo-dirtbike-game.html">Departure Bay<br>Speedway</a><div class="nav-links">'+''.join(f'<a class="wide-link" href="/{f}"'+(' aria-current="page"' if f==p['file'] else '')+f'>{label}</a>' for f,label in links)+'<a class="nav-play" href="/">Play now ↗</a></div></nav>'
 schema={'@context':'https://schema.org','@graph':[place,game,{'@type':'WebPage','@id':BASE+'/'+p['file']+'#page','url':BASE+'/'+p['file'],'name':p['title'],'description':p['desc'],'inLanguage':'en-CA','about':[{'@id':BASE+'/#game'},{'@id':BASE+'/#departure-bay'}],'contentLocation':{'@id':BASE+'/#departure-bay'},'primaryImageOfPage':{'@type':'ImageObject','url':BASE+'/assets/promo/'+p['hero']+'.jpg','caption':'Illustrated campaign artwork for Departure Bay Speedway.'}}]}
 out=f'''<!doctype html><html lang="en-CA"><head>{google_tag}<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(p['title'])}</title><meta name="description" content="{html.escape(p['desc'],quote=True)}"><link rel="canonical" href="{BASE}/{p['file']}"><meta name="theme-color" content="#101d24"><meta property="og:type" content="website"><meta property="og:locale" content="en_CA"><meta property="og:title" content="{html.escape(p['title'],quote=True)}"><meta property="og:description" content="{html.escape(p['desc'],quote=True)}"><meta property="og:url" content="{BASE}/{p['file']}"><meta property="og:image" content="{BASE}/assets/promo/{p['hero']}.jpg"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/promo/site.css"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><a href="#main" class="skip">Skip to content</a>{nav}<main id="main"><header class="hero {"article-hero" if p["file"] != links[0][0] else ""}"><img src="/assets/promo/{p['hero']}.jpg" alt="Illustrated game hero in a white helmet racing a red dirtbike through Departure Bay" width="1536" height="1024" fetchpriority="high"><div class="hero-copy"><h1>{p['heading']}</h1><p>{p['lead']}</p>{cta}</div><div class="hero-bottom"><span>Nanaimo, Vancouver Island · Fictional campaign art</span><a href="#down-the-road">Take a look around ↓</a></div></header><div id="down-the-road" class="route-ribbon"><span>Country Club</span><span>Departure Bay Road</span><span>The beach, bud</span></div>{p['body']}</main><footer class="footer"><span>Departure Bay Speedway<br>A fictional Nanaimo dirtbike game. Keep the chaos on screen.</span><nav aria-label="Explore the game">{''.join(f'<a href="/{f}">{label}</a>' for f,label in links)}</nav></footer><div class="progress" aria-hidden="true"></div><script src="/promo/site.js" defer></script></body></html>'''
 Path(p['file']).write_text(out)
# Root metadata and accessible links; the game retains its normal startup.
p=Path('index.html');s=p.read_text();s=re.sub(r'    <div class="credit">.*?</div>', '    <!-- Map data © OpenStreetMap contributors. Elevation: NRCan. Buildings: City of Nanaimo. Full sources: assets/CREDITS.md. Not affiliated with Rockstar Games. -->',s)
s=s.replace('<title>Departure Bay Speedway</title>','<title>Departure Bay Speedway | Nanaimo Dirtbike Game</title>')
if 'id="game-seo"' not in s:
 meta=f'''<meta id="game-seo" name="description" content="Play Departure Bay Speedway, a free Nanaimo dirtbike browser game. Ride from Country Club to the beach with seven players, flying Nanaimo bars and local attitude.">
<link rel="canonical" href="{BASE}/"><meta property="og:type" content="website"><meta property="og:title" content="Departure Bay Speedway — Give ’er, Nanaimo"><meta property="og:description" content="A fictional Departure Bay Road dirtbike simulator. Seven riders, Nanaimo bars and a beach finish."><meta property="og:url" content="{BASE}/"><meta property="og:image" content="{BASE}/openingscreen.jpg"><meta name="twitter:card" content="summary_large_image">
<script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':[place,game]},ensure_ascii=False)}</script>'''
 s=s.replace('</title>','</title>\n'+meta,1)
 s=s.replace('    <!-- Map data', '    <nav class="promo-links" aria-label="About Departure Bay Speedway"><a href="/nanaimo-dirtbike-game.html">About the game</a> · <a href="/departure-bay-road.html">Explore the road</a> · <a href="/loud-dirtbikes-nanaimo.html">Neighbourhood noise</a></nav>\n    <!-- Map data')
 s=s.replace('</style>','.promo-links{font:12px/1.7 Arial,sans-serif;margin-top:15px;pointer-events:auto;color:#d5dfe4}.promo-links a{color:inherit;padding:6px;display:inline-block}.promo-links a:focus-visible{outline:2px solid #ffd23f}\n</style>',1)
 s=s.replace('  <script>','  <script>\n    document.querySelector(".promo-links")?.addEventListener("pointerdown",e=>e.stopPropagation());\n    document.querySelector(".promo-links")?.addEventListener("keydown",e=>e.stopPropagation());',1)
if "googletagmanager.com/gtag/js?id=G-HR9RQXCV2F" not in s:
 s=s.replace("<head>", "<head>\n"+google_tag, 1)
p.write_text(s)
Path('sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+BASE+'/'+f+'</loc></url>' for f in ['',*(x[0] for x in links)])+'</urlset>\n')
Path('robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /tools/\nDisallow: /api/\nSitemap: '+BASE+'/sitemap.xml\n')
print('Built 3 promotional pages, game metadata, sitemap and robots.txt')
