import {register} from 'node:module';import assert from 'node:assert/strict';
const base=new URL('../',import.meta.url).href;register('data:text/javascript,'+encodeURIComponent(`export async function resolve(s,c,next){if(s==='three')return {url:${JSON.stringify(base)}+'lib/build/three.module.js',shortCircuit:true};if(s.startsWith('three/addons/'))return {url:${JSON.stringify(base)}+'lib/examples/jsm/'+s.slice(13),shortCircuit:true};return next(s,c)}`),import.meta.url);
const THREE=await import('three');const {Police,buildPoliceOfficer,animatePoliceOfficer}=await import('../src/police.js');
const model=buildPoliceOfficer();model.traverse(o=>{if(o.geometry)for(const a of Object.values(o.geometry.attributes))assert(a.array.every(Number.isFinite));});for(let t=0;t<3;t+=.05){animatePoliceOfficer(model,t,'run');model.updateMatrixWorld();model.traverse(o=>assert(o.matrixWorld.elements.every(Number.isFinite)));}
const scene=new THREE.Scene(),terrain={roadDeck:()=>({d:0,hw:4,y:2}),meshHeight:()=>2};let hits=0;const police=new Police(scene,terrain,{onShot:()=>hits++});const car={type:'rcmp',active:true,gen:1,x:0,y:2,z:0,heading:0,v:10};const player={pos:new THREE.Vector3(-1.55,2,-9)};
assert(police.trigger(car));assert(!police.trigger(car));assert.equal(car.v,0);assert.equal(police.encounters[0].officer.position.y,2);
for(let i=0;i<20;i++)police.update(.05,player);assert.equal(hits,0,'exit and aim grace');for(let i=0;i<180;i++)police.update(.05,player);assert(hits>0,'stationary exposed player hit');assert(hits<4,'cooldown limits hits');
const before=hits;police.isBlocked=()=>true;for(let i=0;i<100;i++)police.update(.05,player);assert.equal(hits,before,'cover blocks fire');car.gen++;police.update(.05,player);assert.equal(police.encounters.length,0,'retired generation cleaned');
car.policeStopped=false;police.isBlocked=()=>false;assert(police.trigger(car));for(let i=0;i<501;i++)police.update(.05,player);assert.equal(police.encounters.length,0,'encounter expires');assert.equal(car.policeStopped,false);assert(police.trigger(car));police.reset();assert.equal(scene.children.length,0,'all encounter resources detached');assert.equal(car.policeStopped,false);
console.log('PASS: finite officer rig, ground contact, trigger deduplication, aim grace, paced shots, cover, generation retirement, expiry, reset');
