import {PLAYER_COLORS,PLAYER_COLOR_NAMES} from './player-colors.js';
import {waitingRps} from './waiting-rps.js';
// Admission UI is separate from the race HUD so a full room cannot start physics.
export function multiplayerUI(game){
 const style=document.createElement('style');style.textContent=`
 .room-name{display:flex;flex-direction:column;gap:12px;margin:24px 0}.room-name[hidden]{display:none}.room-name input{padding:14px;border:2px solid #7793a5;border-radius:6px;background:#182e3b;color:white;font:inherit;text-align:center}.room-name input:focus{outline:3px solid #ffda76;outline-offset:3px}
 .room-panel{overflow-y:auto;position:fixed;inset:0;z-index:1200;background:rgba(9,16,22,.94);display:grid;place-items:center;color:#fff;font:18px system-ui;text-align:center;padding:24px}.room-panel[hidden],.room-hud[hidden]{display:none}.room-card{max-width:580px}.room-card h2{font-size:clamp(28px,5vw,48px);line-height:1.1;margin:0 0 20px}.room-card p{color:#d5dfe4;line-height:1.5}.room-panel button,.room-hud button{cursor:pointer;color:white;background:#8e2428;border:1px solid #d38d89;border-radius:5px;padding:10px 18px;font:inherit;margin:8px}.room-hud{position:fixed;left:16px;top:100px;z-index:95;color:#fff;background:#15212bda;border-radius:6px;padding:8px 12px;font:13px system-ui}.room-hud button{font-size:12px;padding:4px 8px;margin:0 0 0 12px}
 .rps-tempo{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:14px 0}.rps-tempo strong{color:#ffda76;font-size:24px;min-width:150px}.room-panel .rps-tempo button{font-size:12px;padding:8px;margin:0}.rps-beats{display:flex;gap:5px;justify-content:center}.rps-beats i{font-style:normal;display:grid;place-items:center;width:24px;height:24px;border-radius:50%;background:#314a58;color:#c4d6df;font-size:12px}.rps-beats i:nth-child(9){margin-left:12px}.rps-beats i.active{background:#ffda76;color:#182731;box-shadow:0 0 18px #ffda7655}.rps-duel>div{display:flex;flex-direction:column;align-items:center;gap:8px;min-width:92px}.rps-duel>div>span{display:block;font-size:64px;filter:drop-shadow(0 8px 5px #0005);transform-origin:50% 85%}.waiting-rps[data-result="win"] .rps-duel>div:first-child{filter:drop-shadow(0 0 12px #32d58399)}.room-panel .rps-choices button[aria-pressed="true"]{background:#ffda76;color:#192c36;border-color:#fff0ba;box-shadow:0 0 15px #ffda7633}.room-panel .rps-choices button:disabled{opacity:.65;cursor:default}.rps-choices button{transition:background .15s,box-shadow .15s}@media(max-width:420px){.rps-tempo strong{font-size:18px;min-width:0}.rps-beats{gap:3px}.rps-beats i{width:19px;height:19px}.rps-duel>div>span{font-size:48px}}
 .waiting-rps{margin:22px 0 14px;padding:20px;border:1px solid #4d6674;border-radius:12px;background:#1a2b36}.waiting-rps[hidden]{display:none}.waiting-rps h3{margin:0;font-size:22px}.waiting-rps .rps-hint{font-size:14px;margin:8px 0}.rps-duel{display:flex;justify-content:center;align-items:center;gap:36px;margin:14px 0}.rps-duel>span{font-size:46px;min-width:70px}.rps-duel small{font-size:13px;color:#9bb3c1}.rps-choices{display:flex;justify-content:center;gap:8px}.room-panel .rps-choices button{display:flex;flex-direction:column;align-items:center;gap:6px;flex:1;margin:0;padding:10px 6px;background:#294453;border-color:#6d96a9;font-size:14px}.rps-choices button span{font-size:30px}.rps-choices button:hover{background:#3c6173}.room-panel button:focus-visible{outline:3px solid #ffda76;outline-offset:3px}.waiting-rps .rps-result{font-size:15px;min-height:44px;margin:14px 0 8px;color:#fff}.rps-score{display:flex;justify-content:center;gap:9px;font-size:13px;color:#bcd0dd}.rps-score span{margin:0 12px}.rps-score b{color:#ffda76}@media(max-height:760px){.room-panel{display:block}.room-card{margin:20px auto}.room-card h2{font-size:30px}.waiting-rps{padding:12px;margin:12px 0}.rps-duel{margin:8px 0}.rps-duel>span{font-size:32px}}
 `;document.head.append(style);
 const panel=document.createElement('section');panel.className='room-panel';panel.hidden=true;panel.setAttribute('aria-live','polite');
 panel.innerHTML='<div class="room-card"><h2></h2><p></p><button type="button" data-retry hidden>Try again, bud</button><button type="button" data-cancel>Back to title</button></div>';
 const hud=document.createElement('div');hud.className='room-hud';hud.hidden=true;hud.innerHTML='<span></span><button type="button">Leave ride</button>';document.body.append(panel,hud);
 for(const el of [panel,hud]){el.addEventListener('pointerdown',e=>e.stopPropagation());el.addEventListener('keydown',e=>e.stopPropagation());}
 const nameForm=document.createElement('form');nameForm.className='room-name';nameForm.hidden=true;
 nameForm.innerHTML='<label for="rider-display-name">Your rider name</label><input id="rider-display-name" name="riderName" maxlength="24" required autocomplete="nickname" placeholder="e.g. Nanaimo Ned"><button type="submit">Let’s ride, bud!</button>';
 panel.querySelector('[data-retry]').before(nameForm);
 const nameInput=nameForm.querySelector('input');
 nameForm.onsubmit=e=>{e.preventDefault();const name=nameInput.value.replace(/[\u0000-\u001f\u007f<>]/g,'').trim().slice(0,24);if(!name){nameInput.value='';nameInput.reportValidity();return;}game.multiplayer.name=name;try{localStorage.setItem('departure-rider-name',name);}catch{}nameForm.hidden=true;game.multiplayer.join();};
 const rpsHost=document.createElement('div');panel.querySelector('[data-retry]').before(rpsHost);
 const rps=waitingRps(rpsHost);
 const retry=panel.querySelector('[data-retry]'),title=panel.querySelector('h2'),detail=panel.querySelector('p');
 function show(heading,text,canRetry=false){nameForm.hidden=true;game.el.title.classList.add('hidden');panel.hidden=false;title.textContent=heading;detail.textContent=text;retry.hidden=!canRetry;hud.hidden=true;}
 function back(){rps.hide();rps.reset();game.multiplayer.leave();panel.hidden=true;hud.hidden=true;game.state='title';game.keys={};game.player.v=0;game.police?.reset();game.el.hud.classList.add('hidden');game.el.finish.classList.add('hidden');game.el.title.classList.remove('hidden');}
 panel.querySelector('[data-cancel]').onclick=back;hud.querySelector('button').onclick=back;retry.onclick=()=>game.multiplayer.join();
 return {
  enterName(){rps.hide();show('What do we call ya, bud?','Other riders will see this name above your bike.');nameForm.hidden=false;try{nameInput.value=localStorage.getItem('departure-rider-name')||'';}catch{}nameInput.focus();},
  joining(){rps.hide();rps.reset();show('Joining the ride, bud…','Finding you a spot on Departure Bay Road.');},
  admitted(){rps.hide();panel.hidden=true;hud.hidden=false;game.startRide();},
  waiting(info){show('Wait your turn, punk.','Only 7 at a time on this biotch. You’re '+(info.queuePosition?`#${info.queuePosition} in line.`:'in line.')+' We’ll start your ride when a spot opens.');rps.show();},
  disconnected(){rps.hide();game.state='title';game.keys={};game.player.v=0;game.el.hud.classList.add('hidden');show('Lost the connection, bud.','Your ride is paused. Rejoin to get back on the road.',true);},
  update(room){if(room.status==='joining'&&panel.hidden)this.joining();hud.hidden=room.status!=='active';if(!hud.hidden){hud.querySelector('span').textContent=`${room.online} / 7 riders online · You: ${room.name||PLAYER_COLOR_NAMES[room.slot]||'Rider'}`;hud.style.borderLeft=`4px solid ${PLAYER_COLORS[room.slot]||'#fff'}`;}}
 };
}
